'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORAGE='carvello.activeProject.v11';
const state={project:null,scope:'piece',tool:'select',selectedPiece:null,selectedCab:null,prop:'piece',history:[],future:[],measureA:null,measureB:null,drag:null,camera:{yaw:-0.58,pitch:-0.30,dist:2900,target:[0,0,600]},render:'pbr'};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)); const rad=d=>d*Math.PI/180;
function uid(p='id'){return p+'_'+Math.random().toString(36).slice(2,8)}
function defaultProject(name='Proiect nou'){let p={version:11,name,created:new Date().toISOString(),cabinets:[]};p.cabinets.push(makeCabinet('base',600,720,560,0,0,0));return p}
function makeCabinet(type,w,h,d,x=0,y=0,z=0){let id=uid('C');let c={id,name:(type==='base'?'Inferior':type==='upper'?'Suspendat':'Coloană')+' '+w,type,w,h,d,x,y,z:type==='upper'?1400:z,rz:0,pieces:[]};let t=18,back=8;function P(name,kind,px,py,pz,pw,pd,ph,band=[]){c.pieces.push({id:uid('P'),name,kind,x:px,y:py,z:pz,w:pw,d:pd,h:ph,rz:0,band});}
P('Lateral stânga','side',-w/2+t/2,0,h/2,t,d,h,['front']);P('Lateral dreapta','side',w/2-t/2,0,h/2,t,d,h,['front']);P('Fund','bottom',0,0,t/2,w-2*t,d,t,['front']);P('Traversă sus','top',0,d/2-55,h-t/2,w-2*t,110,t,['front']);P('Spate','back',0,d/2-back/2,h/2,w-2*t,back,h-2*t,[]);P('Poliță','shelf',0,0,h*0.50,w-2*t,d-20,t,['front']);P('Front ușă','front',0,-d/2-10,h/2,w-4,h-0,18,['all']);return c}
function saveLocal(){localStorage.setItem(STORAGE,JSON.stringify(state.project))}
function loadLocal(){try{let s=localStorage.getItem(STORAGE);state.project=s?JSON.parse(s):defaultProject();}catch(e){state.project=defaultProject()} }
function pushHistory(){state.history.push(JSON.stringify(state.project));if(state.history.length>60)state.history.shift();state.future.length=0}
function restore(s){state.project=JSON.parse(s);state.selectedPiece=null;state.selectedCab=state.project.cabinets[0]?.id||null;saveLocal();refreshAll()}
function undo(){if(!state.history.length)return toast('Nu există Undo');state.future.push(JSON.stringify(state.project));restore(state.history.pop())}
function redo(){if(!state.future.length)return toast('Nu există Redo');state.history.push(JSON.stringify(state.project));restore(state.future.pop())}
function activeCab(){return state.project.cabinets.find(c=>c.id===state.selectedCab)||null}
function activePiece(){let c=activeCab();return c?.pieces.find(p=>p.id===state.selectedPiece)||null}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)}
function setTool(t){state.tool=t;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$('#hudMode').textContent=(state.scope==='piece'?'Piesă':'Corp')+' · '+({select:'Select',move:'Move',rotate:'Rotate',measure:'Measure'})[t];$('#hint').textContent=t==='move'?'Drag = X/Z · Alt+Drag = Y':t==='rotate'?'Drag stânga/dreapta = rotație Z':t==='measure'?'Selectează două piese pentru distanță':'Click pentru selecție · rotiță = zoom · click dreapta = orbit';}
function setScope(s){state.scope=s;$('#scopeSeg').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.scope===s));if(s==='cabinet'){state.selectedPiece=null;state.prop='cabinet'}else state.prop='piece';syncPropTabs();refreshTree();refreshProps();setTool(state.tool)}
function syncPropTabs(){ $$('#propTabs button').forEach(b=>b.classList.toggle('active',b.dataset.prop===state.prop));$('#propState').textContent=state.prop.toUpperCase(); }
function selectCab(id){state.selectedCab=id;state.selectedPiece=null;if(state.scope==='piece'){let c=activeCab();state.selectedPiece=c?.pieces[0]?.id||null}refreshAll()}
function selectPiece(cid,pid){state.selectedCab=cid;state.selectedPiece=pid;if(state.scope==='cabinet')state.selectedPiece=null;refreshAll()}
function refreshAll(){renderTree();refreshProps();syncHeader();draw()}
function syncHeader(){ $('#topProject').textContent=state.project.name;$('#projectCardName').textContent=state.project.name;$('#projectMeta').textContent=state.project.cabinets.length+' '+(state.project.cabinets.length===1?'corp':'corpuri');let c=activeCab(),p=activePiece();$('#hudSel').textContent=state.scope==='cabinet'?(c?c.name:'Niciun corp selectat'):(p?p.name:'Nicio piesă selectată'); }
function renderTree(){let html='';state.project.cabinets.forEach((c,i)=>{let cs=state.selectedCab===c.id&&state.scope==='cabinet';html+=`<div class="treeRow ${cs?'selected':''}" data-cab="${c.id}"><span class="typeIcon">▣</span><b>${esc(c.name)}</b><span class="count">${c.pieces.length} piese</span></div>`;c.pieces.forEach(p=>{let ps=state.selectedPiece===p.id&&state.scope==='piece';html+=`<div class="treeRow indent1 ${ps?'selected':''}" data-cab="${c.id}" data-piece="${p.id}"><span class="typeIcon">◇</span>${esc(p.name)}</div>`})});$('#tree').innerHTML=html;}
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function num(v){return Number(v||0).toFixed(1)}
function refreshProps(){let box=$('#props');if(state.prop==='project'){box.innerHTML=`<div class="section"><h4>Proiect activ</h4><div class="body"><div class="field"><label>Nume</label><input id="prName" value="${esc(state.project.name)}"></div><div class="field"><label>Corpuri</label><input value="${state.project.cabinets.length}" disabled></div></div></div><div class="section"><h4>Acțiuni</h4><div class="body actions"><button class="action" id="prSave">Salvează</button><button class="action danger" id="prNew">Proiect nou</button></div></div>`;$('#prName').onchange=e=>{pushHistory();state.project.name=e.target.value||'Proiect';saveLocal();syncHeader()};$('#prSave').onclick=exportProject;$('#prNew').onclick=()=>showModal('#newModal');return}
if(state.prop==='cabinet'){let c=activeCab();if(!c){box.innerHTML='<div class="empty">Selectează un corp.</div>';return}box.innerHTML=`<div class="section"><h4>${esc(c.name)}</h4><div class="body"><div class="field"><label>Lățime</label><input data-cf="w" type="number" value="${c.w}"></div><div class="field"><label>Înălțime</label><input data-cf="h" type="number" value="${c.h}"></div><div class="field"><label>Adâncime</label><input data-cf="d" type="number" value="${c.d}"></div></div></div><div class="section"><h4>Poziție</h4><div class="body"><div class="field"><label>X</label><input data-cf="x" type="number" value="${num(c.x)}"></div><div class="field"><label>Y</label><input data-cf="y" type="number" value="${num(c.y)}"></div><div class="field"><label>Z</label><input data-cf="z" type="number" value="${num(c.z)}"></div><div class="field"><label>Rotație Z</label><input data-cf="rz" type="number" value="${num(c.rz)}"></div></div></div><div class="section"><h4>Acțiuni</h4><div class="body actions"><button class="action" id="dupCab">Duplică</button><button class="action" id="fitCab">Încadrează</button><button class="action danger" id="delCab">Șterge</button></div></div>`;$$('[data-cf]').forEach(i=>i.onchange=e=>{pushHistory();let f=e.target.dataset.cf;c[f]=Number(e.target.value);if(['w','h','d'].includes(f)){let nc=makeCabinet(c.type,c.w,c.h,c.d,c.x,c.y,c.z);nc.id=c.id;nc.name=c.name;nc.rz=c.rz;Object.assign(c,nc)}saveLocal();refreshAll()});$('#dupCab').onclick=duplicateCab;$('#fitCab').onclick=fit;$('#delCab').onclick=deleteCab;return}
let p=activePiece(),c=activeCab();if(!p||!c){box.innerHTML='<div class="empty">Selectează o piesă.</div>';return}box.innerHTML=`<div class="section"><h4>${esc(p.name)}</h4><div class="body"><div class="field"><label>Tip</label><input value="${p.kind}" disabled></div><div class="field"><label>Lățime</label><input data-pf="w" type="number" value="${num(p.w)}"></div><div class="field"><label>Înălțime</label><input data-pf="h" type="number" value="${num(p.h)}"></div><div class="field"><label>Grosime</label><input data-pf="d" type="number" value="${num(p.d)}"></div></div></div><div class="section"><h4>Poziție locală</h4><div class="body"><div class="field"><label>X</label><input data-pf="x" type="number" value="${num(p.x)}"></div><div class="field"><label>Y</label><input data-pf="y" type="number" value="${num(p.y)}"></div><div class="field"><label>Z</label><input data-pf="z" type="number" value="${num(p.z)}"></div><div class="field"><label>Rotație Z</label><input data-pf="rz" type="number" value="${num(p.rz)}"></div></div></div><div class="section"><h4>Canturi</h4><div class="body"><div style="color:#a9bdca">${p.band.length?p.band.join(', '):'fără cant'}</div></div></div>`;$$('[data-pf]').forEach(i=>i.onchange=e=>{pushHistory();p[e.target.dataset.pf]=Number(e.target.value);saveLocal();refreshAll()});}
function duplicateCab(){let c=activeCab();if(!c)return;pushHistory();let n=JSON.parse(JSON.stringify(c));n.id=uid('C');n.name=c.name+' copie';n.x+=c.w+80;n.pieces.forEach(p=>p.id=uid('P'));state.project.cabinets.push(n);state.selectedCab=n.id;state.selectedPiece=null;saveLocal();fit();refreshAll();toast('Corp duplicat')}
function deleteCab(){let c=activeCab();if(!c)return;if(state.project.cabinets.length===1)return toast('Proiectul trebuie să aibă cel puțin un corp');pushHistory();state.project.cabinets=state.project.cabinets.filter(x=>x.id!==c.id);state.selectedCab=state.project.cabinets[0].id;state.selectedPiece=null;saveLocal();refreshAll()}
function exportProject(){let blob=new Blob([JSON.stringify(state.project,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.project.name.replace(/[^a-z0-9_-]+/gi,'_')||'Carvello')+'.carvello';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Proiect salvat')}
function importProject(file){let r=new FileReader();r.onload=()=>{try{let p=JSON.parse(r.result);if(!Array.isArray(p.cabinets))throw 0;state.project=p;state.history=[];state.future=[];state.selectedCab=p.cabinets[0]?.id||null;state.selectedPiece=null;saveLocal();fit();refreshAll();toast('Proiect încărcat')}catch(e){toast('Fișier proiect invalid')}};r.readAsText(file)}
function showModal(s){$(s).classList.add('show')}function hideModals(){$$('.modalBack').forEach(x=>x.classList.remove('show'))}
function newProject(name){localStorage.removeItem(STORAGE);state.project=defaultProject(name||'Proiect nou');state.history=[];state.future=[];state.selectedCab=state.project.cabinets[0].id;state.selectedPiece=state.project.cabinets[0].pieces[0].id;saveLocal();fit();refreshAll();toast('Proiect nou creat')}
function addCab(){let type=$('#cabType').value,w=Number($('#cabW').value),h=Number($('#cabH').value),d=Number($('#cabD').value);if(!(w>100&&h>100&&d>100))return toast('Dimensiuni invalide');pushHistory();let maxX=state.project.cabinets.reduce((m,c)=>Math.max(m,c.x+c.w/2),-w/2);let c=makeCabinet(type,w,h,d,maxX+w/2+80,0,0);state.project.cabinets.push(c);state.selectedCab=c.id;state.selectedPiece=null;saveLocal();fit();refreshAll();toast('Corp adăugat')}
