// WebGL renderer
const canvas=$('#gl'), gl=canvas.getContext('webgl',{antialias:true,alpha:false});
let prog,lineProg,bufPos,bufNorm,edgeBuf;
const VS=`attribute vec3 aPos;attribute vec3 aNorm;uniform mat4 uMVP;uniform mat4 uModel;varying vec3 vN;void main(){gl_Position=uMVP*vec4(aPos,1.0);vN=mat3(uModel)*aNorm;}`;
const FS=`precision mediump float;uniform vec4 uColor;uniform vec3 uLight;uniform float uXray;varying vec3 vN;void main(){float d=max(.0,dot(normalize(vN),normalize(uLight)));float l=.46+d*.54;vec3 c=uColor.rgb*l;gl_FragColor=vec4(c,uColor.a*uXray);}`;
const LVS=`attribute vec3 aPos;uniform mat4 uMVP;void main(){gl_Position=uMVP*vec4(aPos,1.0);}`;const LFS=`precision mediump float;uniform vec4 uColor;void main(){gl_FragColor=uColor;}`;
function shader(t,s){let h=gl.createShader(t);gl.shaderSource(h,s);gl.compileShader(h);if(!gl.getShaderParameter(h,gl.COMPILE_STATUS))console.error(gl.getShaderInfoLog(h));return h}function program(v,f){let p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,v));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,f));gl.linkProgram(p);return p}
const cube=[-0.5,-0.5,-0.5,0,0,-1,.5,-.5,-.5,0,0,-1,.5,.5,-.5,0,0,-1,-.5,-.5,-.5,0,0,-1,.5,.5,-.5,0,0,-1,-.5,.5,-.5,0,0,-1,-.5,-.5,.5,0,0,1,.5,.5,.5,0,0,1,.5,-.5,.5,0,0,1,-.5,-.5,.5,0,0,1,-.5,.5,.5,0,0,1,.5,.5,.5,0,0,1,-.5,-.5,-.5,-1,0,0,-.5,.5,-.5,-1,0,0,-.5,.5,.5,-1,0,0,-.5,-.5,-.5,-1,0,0,-.5,.5,.5,-1,0,0,-.5,-.5,.5,-1,0,0,.5,-.5,-.5,1,0,0,.5,.5,.5,1,0,0,.5,.5,-.5,1,0,0,.5,-.5,-.5,1,0,0,.5,-.5,.5,1,0,0,.5,.5,.5,1,0,0,-.5,-.5,-.5,0,-1,0,-.5,-.5,.5,0,-1,0,.5,-.5,.5,0,-1,0,-.5,-.5,-.5,0,-1,0,.5,-.5,.5,0,-1,0,.5,-.5,-.5,0,-1,0,-.5,.5,-.5,0,1,0,.5,.5,.5,0,1,0,-.5,.5,.5,0,1,0,-.5,.5,-.5,0,1,0,.5,.5,-.5,0,1,0,.5,.5,.5,0,1,0];
const edges=[-.5,-.5,-.5,.5,-.5,-.5,.5,-.5,-.5,.5,.5,-.5,.5,.5,-.5,-.5,.5,-.5,-.5,.5,-.5,-.5,-.5,-.5,-.5,-.5,.5,.5,-.5,.5,.5,-.5,.5,.5,.5,.5,.5,.5,.5,-.5,.5,.5,-.5,.5,-.5,-.5,.5,-.5,-.5,-.5,-.5,-.5,-.5,.5,.5,-.5,-.5,.5,-.5,.5,.5,.5,.5,.5,.5,-.5,.5,.5,-.5,-.5,.5,-.5,-.5,-.5,-.5,.5,.5,-.5,-.5,.5,.5,-.5,.5,.5,.5,.5,-.5,.5,-.5,.5];
function initGL(){if(!gl){toast('WebGL indisponibil');return}prog=program(VS,FS);lineProg=program(LVS,LFS);bufPos=gl.createBuffer();bufNorm=gl.createBuffer();let pos=[],nor=[];for(let i=0;i<cube.length;i+=6){pos.push(cube[i],cube[i+1],cube[i+2]);nor.push(cube[i+3],cube[i+4],cube[i+5])}gl.bindBuffer(gl.ARRAY_BUFFER,bufPos);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(pos),gl.STATIC_DRAW);bufNorm=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,bufNorm);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(nor),gl.STATIC_DRAW);edgeBuf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,edgeBuf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(edges),gl.STATIC_DRAW);gl.enable(gl.DEPTH_TEST);}
function I(){return [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}function mul(a,b){let r=new Array(16).fill(0);for(let c=0;c<4;c++)for(let rr=0;rr<4;rr++)for(let k=0;k<4;k++)r[c*4+rr]+=a[k*4+rr]*b[c*4+k];return r}function trans(x,y,z){let m=I();m[12]=x;m[13]=y;m[14]=z;return m}function scale(x,y,z){let m=I();m[0]=x;m[5]=y;m[10]=z;return m}function rotY(a){let c=Math.cos(a),s=Math.sin(a),m=I();m[0]=c;m[8]=s;m[2]=-s;m[10]=c;return m}function rotX(a){let c=Math.cos(a),s=Math.sin(a),m=I();m[5]=c;m[9]=-s;m[6]=s;m[10]=c;return m}function persp(f,a,n,f2){let t=1/Math.tan(f/2),m=new Array(16).fill(0);m[0]=t/a;m[5]=t;m[10]=(f2+n)/(n-f2);m[11]=-1;m[14]=2*f2*n/(n-f2);return m}
function viewMat(){let c=state.camera;return mul(trans(0,0,-c.dist),mul(rotX(c.pitch),mul(rotY(c.yaw),trans(-c.target[0],-c.target[2],-c.target[1]))))}
function cabinetModel(c){return mul(trans(c.x,c.z,c.y),rotY(-rad(c.rz)))}function pieceModel(c,p){return mul(cabinetModel(c),mul(trans(p.x,p.z,p.y),mul(rotY(-rad(p.rz||0)),scale(p.w,p.h,p.d))))}
function resize(){let dpr=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h)}
function colorFor(p,mode){if(mode==='edge')return p.kind==='front'?[.78,.80,.80,1]:[.62,.68,.70,1];if(p.kind==='back')return [.35,.31,.23,1];if(p.kind==='front')return [.88,.87,.82,1];if(p.kind==='shelf')return [.79,.80,.77,1];return [.82,.82,.78,1]}
function drawBox(model,color,edgeColor,alpha=1,wireOnly=false){let proj=persp(rad(42),canvas.width/canvas.height,1,20000),mvp=mul(proj,mul(viewMat(),model));if(!wireOnly){gl.useProgram(prog);let lp=gl.getAttribLocation(prog,'aPos'),ln=gl.getAttribLocation(prog,'aNorm');gl.bindBuffer(gl.ARRAY_BUFFER,bufPos);gl.enableVertexAttribArray(lp);gl.vertexAttribPointer(lp,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,bufNorm);gl.enableVertexAttribArray(ln);gl.vertexAttribPointer(ln,3,gl.FLOAT,false,0,0);gl.uniformMatrix4fv(gl.getUniformLocation(prog,'uMVP'),false,new Float32Array(mvp));gl.uniformMatrix4fv(gl.getUniformLocation(prog,'uModel'),false,new Float32Array(model));gl.uniform4f(gl.getUniformLocation(prog,'uColor'),color[0],color[1],color[2],color[3]);gl.uniform3f(gl.getUniformLocation(prog,'uLight'),-.35,.8,.55);gl.uniform1f(gl.getUniformLocation(prog,'uXray'),alpha);gl.drawArrays(gl.TRIANGLES,0,36)}if(edgeColor){gl.useProgram(lineProg);let a=gl.getAttribLocation(lineProg,'aPos');gl.bindBuffer(gl.ARRAY_BUFFER,edgeBuf);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,0,0);gl.uniformMatrix4fv(gl.getUniformLocation(lineProg,'uMVP'),false,new Float32Array(mvp));gl.uniform4f(gl.getUniformLocation(lineProg,'uColor'),...edgeColor);gl.drawArrays(gl.LINES,0,edges.length/3)}}
function drawGrid(){if(state.render==='presentation')return;gl.useProgram(lineProg);let verts=[];for(let x=-3000;x<=3000;x+=100)verts.push(x,0,-3000,x,0,3000);for(let z=-3000;z<=3000;z+=100)verts.push(-3000,0,z,3000,0,z);let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STREAM_DRAW);let a=gl.getAttribLocation(lineProg,'aPos');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,0,0);let mvp=mul(persp(rad(42),canvas.width/canvas.height,1,20000),viewMat());gl.uniformMatrix4fv(gl.getUniformLocation(lineProg,'uMVP'),false,new Float32Array(mvp));gl.uniform4f(gl.getUniformLocation(lineProg,'uColor'),.12,.25,.32,1);gl.drawArrays(gl.LINES,0,verts.length/3);gl.deleteBuffer(b)}
function draw(){if(!gl)return;resize();let mode=state.render;gl.clearColor(mode==='presentation'?.12:.025,mode==='presentation'?.14:.065,mode==='presentation'?.15:.095,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);if(mode==='xray'){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false)}else{gl.disable(gl.BLEND);gl.depthMask(true)}drawGrid();for(let c of state.project.cabinets){for(let p of c.pieces){let sel=(state.scope==='piece'&&state.selectedPiece===p.id)||(state.scope==='cabinet'&&state.selectedCab===c.id),edge=sel?[1,.55,.1,1]:mode==='shaded'?[.25,.42,.5,1]:mode==='wire'?[.65,.85,.95,1]:mode==='presentation'?[.28,.30,.31,1]:[.18,.28,.32,1];drawBox(pieceModel(c,p),colorFor(p,mode),edge,mode==='xray'?.28:1,mode==='wire');if(mode==='edge'&&p.band.length){let bandColor=[.95,.54,.08,1],bw=2;if(p.band.includes('front')||p.band.includes('all')){let bm=mul(cabinetModel(c),mul(trans(p.x,p.z,p.y-p.d/2-1),scale(p.w,p.h,bw)));drawBox(bm,bandColor,null)}}}}if(mode==='xray')gl.depthMask(true)}
function fit(){if(!state.project.cabinets.length)return;let minX=1e9,maxX=-1e9,minZ=1e9,maxZ=-1e9;state.project.cabinets.forEach(c=>{minX=Math.min(minX,c.x-c.w/2);maxX=Math.max(maxX,c.x+c.w/2);minZ=Math.min(minZ,c.z);maxZ=Math.max(maxZ,c.z+c.h)});state.camera.target=[(minX+maxX)/2,0,(minZ+maxZ)/2];state.camera.dist=Math.max(1500,(maxX-minX)*1.45,(maxZ-minZ)*1.9);draw()}
function front(){state.camera.yaw=0;state.camera.pitch=0;fit()}function iso(){state.camera.yaw=-.65;state.camera.pitch=-.34;fit()}
function projectPoint(x,y,z){let vp=mul(persp(rad(42),canvas.width/canvas.height,1,20000),viewMat()),v=[x,z,y,1],o=[0,0,0,0];for(let r=0;r<4;r++)o[r]=vp[r]*v[0]+vp[4+r]*v[1]+vp[8+r]*v[2]+vp[12+r]*v[3];if(o[3]<=0)return null;return{x:(o[0]/o[3]*.5+.5)*canvas.clientWidth,y:(1-(o[1]/o[3]*.5+.5))*canvas.clientHeight}}
function worldPieceCenter(c,p){let a=rad(c.rz),cx=c.x+Math.cos(a)*p.x+Math.sin(a)*p.y,cy=c.y-Math.sin(a)*p.x+Math.cos(a)*p.y;return[cx,cy,c.z+p.z]}
function pick(clientX,clientY){let r=canvas.getBoundingClientRect(),x=clientX-r.left,y=clientY-r.top,best=null,bestD=1e9;for(let c of state.project.cabinets)for(let p of c.pieces){let q=worldPieceCenter(c,p),s=projectPoint(q[0],q[1],q[2]);if(!s)continue;let d=Math.hypot(s.x-x,s.y-y);if(d<bestD){bestD=d;best={c,p}}}return bestD<120?best:null}
function measureClick(hit){if(!hit)return;if(!state.measureA){state.measureA=worldPieceCenter(hit.c,hit.p);toast('Primul punct selectat');return}state.measureB=worldPieceCenter(hit.c,hit.p);let a=state.measureA,b=state.measureB,d=Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2]);toast('Distanță: '+d.toFixed(1)+' mm');state.measureA=null;state.measureB=null}
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('mousedown',e=>{let hit=pick(e.clientX,e.clientY);if(e.button===2){state.drag={kind:'orbit',x:e.clientX,y:e.clientY,yaw:state.camera.yaw,pitch:state.camera.pitch};return}if(state.tool==='measure'){measureClick(hit);return}if(state.tool==='select'){if(hit){if(state.scope==='cabinet')selectCab(hit.c.id);else selectPiece(hit.c.id,hit.p.id)}return}if(!hit&&state.scope==='piece')return;let c=hit?.c||activeCab(),p=hit?.p||activePiece();if(!c)return;if(state.scope==='cabinet'){state.selectedCab=c.id;state.selectedPiece=null}else if(hit){state.selectedCab=c.id;state.selectedPiece=p.id}pushHistory();state.drag={kind:state.tool,x:e.clientX,y:e.clientY,cid:c.id,pid:state.scope==='piece'?p?.id:null,base:JSON.stringify({c,p})};refreshAll()});
window.addEventListener('mousemove',e=>{let d=state.drag;if(!d)return;let dx=e.clientX-d.x,dy=e.clientY-d.y;if(d.kind==='orbit'){state.camera.yaw=d.yaw+dx*.006;state.camera.pitch=clamp(d.pitch+dy*.006,-1.25,1.25);draw();return}let c=state.project.cabinets.find(x=>x.id===d.cid);if(!c)return;let b=JSON.parse(d.base),scalePx=state.camera.dist/1100;if(d.kind==='move'){if(state.scope==='cabinet'){c.x=b.c.x+dx*scalePx;c[e.altKey?'y':'z']=e.altKey?b.c.y-dy*scalePx:b.c.z-dy*scalePx}else{let p=c.pieces.find(x=>x.id===d.pid);if(!p)return;p.x=b.p.x+dx*scalePx;p[e.altKey?'y':'z']=e.altKey?b.p.y-dy*scalePx:b.p.z-dy*scalePx}}else if(d.kind==='rotate'){if(state.scope==='cabinet')c.rz=b.c.rz+dx*.35;else{let p=c.pieces.find(x=>x.id===d.pid);if(p)p.rz=(b.p.rz||0)+dx*.35}}saveLocal();syncHeader();refreshProps();draw()});window.addEventListener('mouseup',()=>{if(state.drag){state.drag=null;saveLocal();refreshAll()}});canvas.addEventListener('wheel',e=>{e.preventDefault();state.camera.dist=clamp(state.camera.dist*(e.deltaY>0?1.09:.91),350,12000);draw()},{passive:false});
